### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by ccoenen** [MichaelKreil/rc3-21-map-scraper#1]
Would you consider putting the code (not the data, of course) under a license of your choice? Especially [`generateScreenshot`](https://github.com/MichaelKreil/rc3-21-map-scraper/blob/12a6358d6244ad5277149be7f562b8bd9227e506/1_scrape.js#L134) would be quite useful to be usable outside this project. I would love to transfer this into some kind of CI-runnable script that one could add to a repo that would just automatically create an up-to-date image.

**Comment by askeron** [comment]
+1 - something like MIT would be great ;)

**Comment by MichaelKreil** [comment]
Of course!
c0731ef175b14beca5e326f3bde3eba5b4ce5fb6
